### ISSUE TITLE
Investigate Netify deployment test fails

### ISSUE THREAD

**Issue by andybroomfield** [TechForUK/brexchat#37]
When making Pull Requests, the Netifly deployment tests are failing.
Failure seems to be this
> 12:41:17 PM: Executing user command: hugo --gc --minify --config production.toml
12:41:17 PM: Error: unknown command "production.toml" for "hugo"

**Comment by jt-nti** [comment]
I'm tempted to publish to Netlify using Travis to fix the problem with the lack of the extended Hugo version on Netlify, which would hopefully fix this issue as well

**Comment by jt-nti** [comment]
Fixed in #58
